#print data with end value
print(10,20)
print("naresh")
print("suresh",end=".")
print("kiran",end=",")
print("python",end=";")
print("kiran")
print("teja")
print("Muthyalapati",end=",")
print("Kiranteja")
